apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
spec:
  project: default
  source:
    chart: oauth2-proxy
    helm:
      parameters:
      - name: image.repository
        value: quay.io/oauth2-proxy/oauth2-proxy
      - name: image.tag
        value: v7.1.3
      - name: configSecret.create
        value: "false"
      - name: config.existingSecret
        value: oauth2-proxy
      - name: service.port
        value: "4180"
      - name: extraArgs.provider
        value: oidc
      - name: extraArgs.set-xauthrequest
        value: "true"
      - name: extraArgs.cookie-secure
        value: "true"
      - name: extraArgs.cookie-samesite
        value: lax
      - name: extraArgs.cookie-refresh
        value: 1h
      - name: extraArgs.cookie-expire
        value: 4h
      - name: extraArgs.cookie-name
        value: _oauth2_proxy
      - name: extraArgs.email-domain
        value: "*"
      - name: extraArgs.upstream
        value: "static://200"
      - name: extraArgs.skip-provider-button
        value: "true"
      - name: extraArgs.cookie-domain
        value: .aaw.cloud.statcan.ca
      - name: extraArgs.whitelist-domain
        value: .aaw.cloud.statcan.ca
      - name: extraArgs.oidc-issuer-url
        value: auth.aaw.cloud.statcan.ca
      - name: extraArgs.login-url
        value: "auth.aaw.cloud.statcan.ca/auth"
      - name: extraArgs.oidc-jwks-url
        value: "auth.aaw.cloud.statcan.ca/keys"
      - name: extraArgs.redeem-url
        value: "auth.aaw.cloud.statcan.ca/token"
      - name: extraArgs.skip-oidc-discovery
        value: "true"