apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- configmap.yaml
- envoy-filter.yaml
- statefulset.yaml
resources:
- github.com/kubeflow/manifests/common/oidc-authservice/base?ref=42a19c0825d23149c0edb67757b04a635d6a26f0 #1.3.1
