apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-cleanup-workflows
spec:
  concurrencyPolicy: Allow
  schedule: "0 22 * * 1-5"
  jobTemplate:  
    spec:
      template:
        spec:
          containers:
          - name: cron
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            command:
            - kubectl delete --all-namespaces -l "scheduledworkflows.kubeflow.org/isOwnedByScheduledWorkflow=true" --older 5d 
          restartPolicy: OnFailure
