apiVersion: v1
data:
  secretkey: V1o5dXc4eGVsbWdqL1BUM3Q3eHhzd0RMWjM4eXFRQXRlbmQ4a0tKSHUwYkhOZENtektBQ2N6cDRMVTd2ZGJoWApDcU9CS2kwZXVYVDAyUkU2SU1tL1BpSk4veGVWendhbU1JUDU1UC9jTkN0RFZmMlJUa1plaU45c0dtak1GZ1FCCitwN2dZN2xVZ0hUTkQ3TFJlSWkzaGh2QWZ0Ukw2aDZxbHd0RkNwdnkzdk09
kind: Secret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
