apiVersion: v1
data:
  secretkey: T0UzcElFR3Vva2g4QnVRc3c4ZzAyeTN1aXdPWWp1cVJVRlgwRXUzd1l2MGMyUGk0UEswdTF5eVIxcS9WTDg5dgpuQjBXRUxBNmh5RXl2L3k4WS9xd0NobHJuNmxvVURqWVZFS25tSTZZM0ZzdjE0WnU2WTdLYmpqTmhVOUg3U0hyCkJoc2w3RTc0elRVVDhtOXJrV0NEa1BPTHlMWCtlODRKVlRkV3FZZHdlU0k9
kind: Secret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
