apiVersion: v1
data:
  secretkey: eWxTYzJybm5xeXJaK0VOeEZhNmJyUVNuWVVYcDVsMHV3NGc2ODQ2VWwxdmdtK0ZSWmNqLzU3cXMzeFhMVUpkZApmZ0VsV3FJWXBHUmJ4ZXBjQWtZZXcvVTVnQnBEVDdKejU0THZpZWQzNTh0NWoyUzFNM0xUOTlhL0NoNk9UcHhJCnB2a2JGbTJJczVkc3MwMmFkVGMwYmdldi9EelJPdVlINVQrMFdhQm5oN1k9
kind: Secret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
