apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: $ARGOFLOW_GIT_REPO_URL
    targetRevision: $ARGOFLOW_GIT_REPO_TARGET_REVISION
    path: distribution/istio-resources
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
