apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: << git_repo.url >>
    targetRevision: << git_repo.target_revision >>
    path: distribution/kubecost-resources
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
