apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oidc-auth
  namespace: argocd
spec:
  project: default
  source:
    repoURL: $ARGOFLOW_GIT_REPO_URL
    targetRevision: $ARGOFLOW_GIT_REPO_TARGET_REVISION
    path: distribution/oidc-auth/base
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
