apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: profiles
  namespace: argocd
spec:
  destination:
    namespace: kubeflow
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: http://gitserver.git/argoflow-azure.git
    targetRevision: master
    path: distribution/profiles
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
