apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tensorflow-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: << git_repo.url >>
    targetRevision: << git_repo.target_revision >>
    path: distribution/kubeflow/operators/tensorflow
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
