issuer: https://$ARGOFLOW_SUBDOMAIN_AUTH.$ARGOFLOW_DOMAIN
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  http: 0.0.0.0:5556
logger:
  level: "debug"
  format: text
oauth2:
  skipApprovalScreen: true
expiry:
  signingKeys: "4h"
  idTokens: "1h"
enablePasswordDB: true
staticPasswords:
- email:
  hash:
  # https://github.com/dexidp/dex/pull/1601/commits
  # FIXME: Use hashFromEnv instead
  username:
  userID: "15841185641784"
staticClients:
# https://github.com/dexidp/dex/pull/1664
- id: $ARGOFLOW_DEX_CLIENT_ID
  redirectURIs:
  - "https://$ARGOFLOW_SUBDOMAIN_DASHBOARD.$ARGOFLOW_DOMAIN/oauth2/callback"
  name: 'Dex Login Application'
  secret: $ARGOFLOW_DEX_CLIENT_SECRET
