apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/statcan/argoflow-azure.git
    targetRevision: ee6f1c734c42c94f9c1723f9bc8536d8e512668d
    path: distribution/cert-manager/lets-encrypt-dns-01
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
