apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hive-metastore
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/StatCan/aaw-trino.git'
    path: hive-metastore
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hive-system
  syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true