apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/statcan/argoflow-azure.git
    targetRevision: 75b9142f0367ff8fdacb4b38f8213ce0d793e58e
    path: distribution/istio-resources
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
