apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: profiles
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/statcan/argoflow-azure.git
    targetRevision: 7baff377d6199ee8658cba166d4e129b944787bd
    path: distribution/kubeflow/profiles
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
