apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/instance: aaw-daaas-system
  name: namespace-controller
  namespace: daaas-system
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    name: in-cluster
    namespace: daaas-system
  project: default
  source:
    chart: namespace-controller
    helm:
      releaseName: namespace-controller
      values: |
        image:
          repository: k8scc01covidacr.azurecr.io/namespace-controller
          tag: 949b8b02d837fcebd64a135d103e61486185b1f4
    repoURL: 'https://statcan.github.io/charts'
    targetRevision: 0.0.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
