apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oidc-auth
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/statcan/argoflow-azure.git
    targetRevision: 90b17984544e4c5fae84cbf5a92a2c086b1bd334
    path: distribution/oidc-auth/overlays/dex
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
