apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pytorch-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/statcan/argoflow-azure.git
    targetRevision: 75b9142f0367ff8fdacb4b38f8213ce0d793e58e
    path: distribution/kubeflow/operators/pytorch
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
