apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gateways-issuer
spec:  
  selfSigned:
    $patch: delete
  acme:
    email: $ARGOFLOW_CERT_MANAGER_EMAIL_USER@$ARGOFLOW_CERT_MANAGER_EMAIL_DOMAIN
    server: $ARGOFLOW_CERT_MANAGER_SERVER
    privateKeySecretRef:
      name: gateways-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: $ARGOFLOW_CLOUDFLARE_EMAIL
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
