apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gateways-issuer
spec:  
  selfSigned:
    $patch: delete
  acme:
    email: << cert_manager.email_user >>@<< cert_manager.email_domain >>
    server: << cert_manager.server >>
    privateKeySecretRef:
      name: gateways-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: << cloudflare.email >>
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
