apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: auth-allow-in-cluster-redirect
  namespace: istio-system
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  rules:
  - to:
    - operation:
        hosts:
        - "$ARGOFLOW_SUBDOMAIN_AUTH.$ARGOFLOW_DOMAIN"
        - "$ARGOFLOW_SUBDOMAIN_DASHBOARD.$ARGOFLOW_DOMAIN" # needed for redirect after authentication
        - "$ARGOFLOW_SUBDOMAIN_SERVING.$ARGOFLOW_DOMAIN" # needed for redirect after authentication
        - "*.$ARGOFLOW_SUBDOMAIN_SERVING.$ARGOFLOW_DOMAIN" # needed for redirect after authentication
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: auth-allow-access
  namespace: auth
spec:
  action: ALLOW
  rules:
  - {}
  # - from:
  #   - source:
  #       namespaces:
  #       - auth
  #       - istio-system
