kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgAmwxrghTrBiupFoU4qXtK0Blc2Yy4fzJNJBJ6qEmS6YCZBjL0wqlEr3SZhxJCpxFlBEasLn1pM2r667ln+kj8ew9ludEpcOd8NJ+KefeW1k7Ipe8yB82v8924VNopL1nkublmFL9iYCRdahDfE9CmLv6flAEA5PQSz4gPud+09kORBXbLGlrse7DsDAEYIKz03d2Lm/QUceooVjfAYaS9E47rpWYDM5dGP+Qw0+JZRdxuP8IrhP7yplvNtfeGrBVlxYx/PTBIq1l2vVo91Jq/iTJTIzwYGsNU2RzdnZGlD0VfG39S7R0Mi8IAmSZLR9+H+Jq4RKNwV0klKIqg7mhXIXysslEF0bDZEB/GOUrl9QBe8lGRlr9DXol9nPAB8McXCjZxlBnQacMDjFRKDPAY7Eo4uzOpGLtYkf0Yz2jOb+VhSdAFnzV0RyYaC1sViOGWkaohSkFAwZxduDggRh5duycI7Oy65ekk1DfHw+Vgcz2gCALj6lCMvnhV0Co/4nuAIr256BhZrCk6nn1mPEWcnqSXaSxm5BLddvQ0ks7Rz2AY9m9oPjEDJOnYUhUvEfFmjvD1UUTY0k7EFzGqDlppUSRCuV0OUSRwb9e/ZfsbIoK523NFYSaYY0Uq/RHxR7wOMiotBd3jGJMpcZfyOdk2lb5JTngmiNz9eZ1EPMdF5Lg/NfUOUIae6BLSbNorkvGLu4Gjt
    admin-user: AgBt3F1yLfv5+88rMtMIF8wqwy44XJjfs2UqGAUPS1tVe+y0a9DvwGlt3IPmLqjnDiYpPGaZlGQpHWeSFISuHKDgLJ8uwIhFJWz1JGN1cm/md0DMtSQo4ZzkHKjRV0CDnS2EyEYwYoClLGXQ1H8SKjzfL34sEggOg+1Yvbyg4IivA7MpWxAHFxQ+zjAfe/6xjvArrEd4/x6neHPscmTvvGa6CfRDwRzjAzn1sedpaL3zs7rF3wczaLI4bg+k8Zypld1zzJb1Q/hkcqEq3/PP5QmmHyeTGLlKpePkcTvO3/mSjIeGK+srODnZvy7u09PRXj5ABUresITS3N2KtG+24abuaT2TnJ8fBOfiCSouFVPv37Y6hx4VDyt+GllyZA/m361yenbbZ//SKG/kNS7N15vdsz2je5DCF9ZIHzgIyyKKe0ICg1rAqk7GeStggbCxvzTJi2ORDvn1l6KolkeloUfyrGLD9nOeYejXkJx1/BfPtj8MO8d6sJ82RKT0qaP77bExVeXOnIl2G7EqoV94Hs1EQN2TQT0jcZAre/K9qhNc2yIt4SwNaj+FOOx1kACFYbt2qMFH0cIFw+EzlmfAlTezexxYuaDJHoVcBlIalWx/S9paRP+b/Ee207HdQvaPpBajC01PYRqy/I0qBwUHc8+7rMV3umxGgwvsm2gdMb3eu0jAUAzK5yxSK4A30Ew7lcI4RQ8N
