kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgB75PRsGmNvvd+FuxeOOrqKc9SiauVpo/g26Tds+TVn19SylCF+7FuOfitmBCLNhpYkHhsfMCygY7WeRErOfXKUEXbNpiLNWlF+X2XCIRIx3eWlukVxGxBpMiK5iP+RBVGmODpYUdIr09csELueY4Mn/nJYq1ogF6bB265z0aFsDLAs2Cg5voybmGKmisZyzirTJUt+8hK89kc0+6GzGcyK+dgGJf/BaUKQCQBetSTwRTb6UqhMtyxkkJdNRQ2Df/7US7Iio00EWcpO5Xo7GU8CuDYRkeGEa5KEJB9ty47kK69HPa0dqgS040/wCG814IGAsZq0Zs+TAXLMd7LLA8JLIfxgrCUxBO4b3jw0+ezVD/hxBPvpgZWhZv0TRKfbERPFqORpIHO/5dtkNUWpPXA1KnAI1vBz1nUIrYffw/XEI2Kv1hE1c2jhNAQLT5b9ZxdTJ3IhztEqifQx6ESxde6khlTRhXRLETtIkzxf4Rk2nNUouqEpFfnlpjtOjBtoq9+gkMlWQjLnyz6Kw7DkhF9bqSGw2YwFWStxltfNeCome4smCcGkbXwu6t5z3AzX/QwsWeT3ihIgs9N7fkhjctzpW4v1Hmly5RxCcIt49iDfY2r/viNB+QHPmZ+7aUYpWncdwxHbxVF7AXRpc7h0B2cCiCk/6SHShuWY5babl0bNIdZXzBHrpqWZQJMEIgXlR+Fe1+RqYPFJ
    admin-user: AgBmTeGwlBBZ/+YT+78UdP6/Y2hOScptONB7W1D/x//ZrdVtTvDmLQ6IxJOTZBEyXmT+kMk3ZoGKcATQict7UfNdXAqgEfY2lAvlv4ZWmwLAiN6naWbxNuXhLbZVLoUmZBW+6smacOlXgISNYGgkhtoRKkBP5nskoZoj9Yqh12lNIDxNuIxRJU8wimaRYN5MAf3ZkbBs92h7BF0O0i4oysctDXpOLJLaUxinqAcuM+29lHWDi3qvEhIlJi3UIYxJx8QEiQCqTxLyddZWwHAarD2KBEtANFr+0MrCy0KD8H2N45Q2Y6W5AfDxlT4SDiyMuedeP1Rt1LFm3LmJfsJXwhe7nuLYf+frXYQbkipqQTfNfhNvgJmMMw9CvCwv/7aX0VZJBXQb4Hwz5QfKJY/LGSPOt3hy8RIRf+0xtCa6lnLVzxWj+NyIJtWMXBSfIEh8i1+nTEmqQHdioM3/fgKBnB2in7PdwLO4IrizpZb+tScRMDB8GgFGYTDD0asmbke3NXEu9WO484R+OewLeBJPgP/+vdPSzavBpKqRuoWX1ia2avF5YN4Mx08HTqQQGACRCbEwJ4ezDLOsbzu6VNwXeSvyCnxBHh/7F3B5o266TE2S+v7gd1MSRqWLCgSYIRz6vlL+8hFyc2iRqVZd2j7Fg8kThZASrYvAC0NNdQAG+mq14gcKtqdrIv1y29Awcpz0aGxWnVhU0w==
